name: "Send email for Manga Updates"

on:
  workflow_dispatch:
  schedule:
    # Runs every evening 4 hours
    # GitHub Actions only runs scheduled jobs on the default branch of your repository (usually master or main).
    - cron: "0 */6 * * *"

## Common variables for both jobs
env:
  SMTP2GO_API_KEY: <"insert_your_smtp2go_api_key_here_as_a_secret_in_github_e.g., secrets.SMTP2GO_API_KEY">
  SMTP2GO_TEMPLATE_ID: <"insert_template_id_here">
  NOTIFICATION_EMAIL_RECIPIENT: <"insert_recipient_email_here, it can be your personal email, where you want to receive notifications">
  NOTIFICATION_EMAIL_SENDER: <"insert_sender_email_here, it can be any email you own, from which the notifications will be sent">
  SERIES_DATAFOLDER: <"insert where the data folder is located, e.g., ./data">
  API_ENDPOINT: "https://api.mghcdn.com/graphql"


jobs:
  manual-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run manga-updates binary
        run: |
          LATEST_RELEASE_URL=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ivan-penchev/manga-updates/releases/latest | \
            jq -r '.assets[] | select(.name | contains("linux_amd64")) | .url')

          TEMP_DIR=$RUNNER_TEMP/manga-updates-bin
          mkdir -p "$TEMP_DIR"
          curl -L \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Accept: application/octet-stream' \
            -o "$TEMP_DIR/manga-updates.zip" \
            "$LATEST_RELEASE_URL"
          file "$TEMP_DIR/manga-updates.zip"
          unzip "$TEMP_DIR/manga-updates.zip" -d "$TEMP_DIR"
          
          chmod +x "$TEMP_DIR/manga-updates"

          "$TEMP_DIR/manga-updates"

          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email "$NOTIFICATION_EMAIL_SENDER"
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi

  automatic-workflow-dispatch:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run manga-updates binary
        run: |
          LATEST_RELEASE_URL=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ivan-penchev/manga-updates/releases/latest | \
            jq -r '.assets[] | select(.name | contains("linux_amd64")) | .url')

          TEMP_DIR=$RUNNER_TEMP/manga-updates-bin
          mkdir -p "$TEMP_DIR"
          curl -L \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Accept: application/octet-stream' \
            -o "$TEMP_DIR/manga-updates.zip" \
            "$LATEST_RELEASE_URL"
          file "$TEMP_DIR/manga-updates.zip"
          unzip "$TEMP_DIR/manga-updates.zip" -d "$TEMP_DIR"
          
          chmod +x "$TEMP_DIR/manga-updates"

          "$TEMP_DIR/manga-updates"

          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email "$NOTIFICATION_EMAIL_SENDER"
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi
