name: "Send email for Manga Updates"

on:
  workflow_dispatch:
  schedule:
    # Runs every evening 4 hours
    # GitHub Actions only runs scheduled jobs on the default branch of your repository (usually master or main).
    - cron: "0 */6 * * *"

## Common variables for both jobs
env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_TEMPLATE_ID: d-b4267c4ab110461e8e6cff80ff4aa0ca
  NOTIFICATION_EMAIL_RECIPIENT: thefolenangel@gmail.com
  NOTIFICATION_EMAIL_SENDER: manga@penchev.com
  SERIES_DATAFOLDER: ./data
  API_ENDPOINT: "https://api.mghcdn.com/graphql"


jobs:
  manual-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      
      - name: Run manga-updates binary
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/ivan-penchev/manga-updates/releases/latest | jq -r '.assets[] | select(.name | contains("linux_amd64")) | .browser_download_url')
          curl -L $LATEST_RELEASE_URL -o manga-updates.zip
          unzip manga-updates.zip -d manga-updates
          chmod +x manga-updates/manga-updates
          ./manga-updates/manga-updates
          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email manga@penchev.com
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi

  automatic-workflow-dispatch:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run manga-updates binary
        run: |
          go mod vendor
          go run cmd/manga-updates/main.go
          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email manga@penchev.com
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi
