name: "Send email for Manga Updates"

on:
  workflow_dispatch:
  schedule:
   # Runs every evening 4 hours
   # GitHub Actions only runs scheduled jobs on the default branch of your repository (usually master or main).
    - cron: '0 */4 * * *'

## Common variables for both jobs
env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  manual-workflow-dispatch:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run manga-updates binary
        env:
          SERIES_DATAFOLDER: ./data
        run: |
          go mod vendor
          go run cmd/manga-updates/main.go
          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email manga@penchev.com
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi

  automatic-workflow-dispatch:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run manga-updates binary
        env:
          SERIES_DATAFOLDER: ./data
        run: |
          go mod vendor
          go run cmd/manga-updates/main.go
          if [ -n "$(git status --porcelain)" ]; then
            echo "commiting changes";
            git config --global user.name 'MangaUpdates (Automation)'
            git config --global user.email manga@penchev.com
            git commit -am "Updated state"
            git push
          else
            echo "Nothing to commit";
          fi
          
